# Generated by Django 2.2.9 on 2019-12-25 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Used to determine type of notification e.g. user_mentioned or user_replied', max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('content', models.TextField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('object_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
